name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: test
        run: mvn test
        
      - name: ALL
        run: |
         ls
         
      - name: TARGET
        run: |
         ls target
         
      - name: SITE
        run: |
         ls target/site
         
      - name: JACOCO
        run: |
          ls target/site/jacoco
          
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Tests Report           # Name of the check run which will be created
          path: target/site/jacoco/jacoco.xml   # Path to test results
          reporter: jest-junit        # Format of test results
          
