name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and Test
        run: mvn --batch-mode --update-snapshots package
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.35
        with:
          files: "test-results/**/*.xml"

